output "resource_group_name" {
  value = azurerm_resource_group.main.name
}

output "location" {
  value = var.location
}

# AKS
output "aks_name" {
  value = module.aks.name
}

output "aks_oidc_issuer_url" {
  value = module.aks.oidc_issuer_url
}

# ACR
output "acr_name" {
  value = module.acr.name
}

output "acr_login_server" {
  value = module.acr.login_server
}

# Identity (single UAMI shared by all services via Workload Identity)
output "uami_name" {
  value = module.identity.uami_name
}

output "uami_client_id" {
  value = module.identity.uami_client_id
}

output "uami_principal_id" {
  value = module.identity.uami_principal_id
}

# Postgres
output "postgres_fqdn" {
  value = module.postgres.fqdn
}

output "postgres_databases" {
  value = module.postgres.databases
}

# Service Bus
output "servicebus_namespace" {
  value = module.servicebus.namespace_name
}

output "servicebus_topic" {
  value = module.servicebus.topic_name
}

# Redis
output "redis_hostname" {
  value = module.redis.hostname
}

output "redis_ssl_port" {
  value = module.redis.ssl_port
}

# Storage
output "storage_account_name" {
  value = module.storage.account_name
}

output "storage_blob_endpoint" {
  value = module.storage.blob_endpoint
}

output "storage_images_container" {
  value = module.storage.images_container
}

# Key Vault
output "keyvault_name" {
  value = module.keyvault.name
}

output "keyvault_uri" {
  value = module.keyvault.uri
}

# Observability
output "log_analytics_workspace_id" {
  value = module.observability.law_id
}

output "appinsights_connection_string" {
  value     = module.observability.appinsights_connection_string
  sensitive = true
}

output "appinsights_instrumentation_key" {
  value     = module.observability.appinsights_instrumentation_key
  sensitive = true
}

# Convenience: dump everything into a JSON env file consumed by deploy scripts
output "env_summary" {
  description = "Use: terraform output -raw env_summary > ../../.azure-env.sh"
  value       = <<-EOT
    #!/usr/bin/env bash
    # Auto-generated by terraform output. DO NOT EDIT.
    export AZ_RG="${azurerm_resource_group.main.name}"
    export AZ_LOCATION="${var.location}"
    export AZ_AKS="${module.aks.name}"
    export AZ_ACR="${module.acr.name}"
    export AZ_ACR_LOGIN="${module.acr.login_server}"
    export AZ_UAMI="${module.identity.uami_name}"
    export AZ_UAMI_CLIENT_ID="${module.identity.uami_client_id}"
    export AZ_UAMI_PRINCIPAL_ID="${module.identity.uami_principal_id}"
    export AZ_PG_FQDN="${module.postgres.fqdn}"
    export AZ_SB_NS="${module.servicebus.namespace_name}"
    export AZ_SB_TOPIC="${module.servicebus.topic_name}"
    export AZ_REDIS_HOST="${module.redis.hostname}"
    export AZ_REDIS_PORT="${module.redis.ssl_port}"
    export AZ_STORAGE="${module.storage.account_name}"
    export AZ_STORAGE_BLOB="${module.storage.blob_endpoint}"
    export AZ_STORAGE_CONTAINER="${module.storage.images_container}"
    export AZ_KEYVAULT="${module.keyvault.name}"
    export AZ_LAW_ID="${module.observability.law_id}"
    export AZ_NAMESPACE="${var.kubernetes_namespace}"
  EOT
}
