#!/usr/bin/env bash
# init-names.sh — Generate a 4-char unique suffix and persist .local.env +
# infra/terraform/terraform.tfvars. Idempotent: existing files are left alone.
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

ENV_FILE="${REPO_ROOT}/.local.env"
TFVARS="${REPO_ROOT}/infra/terraform/terraform.tfvars"

step "init-names — generate unique suffix and persist config"

if [[ -f "${ENV_FILE}" ]]; then
  warn "${ENV_FILE} already exists — leaving it alone."
  info "current contents:"
  sed 's/^/    /' "${ENV_FILE}"
  exit 0
fi

substep "Verify Azure sign-in"
if ! az account show >/dev/null 2>&1; then
  die "not signed in. Run: az login"
fi
SUB_ID="$(az account show --query id -o tsv)"
SUB_NAME="$(az account show --query name -o tsv)"
USER_OID="$(az ad signed-in-user show --query id -o tsv)"
USER_UPN="$(az ad signed-in-user show --query userPrincipalName -o tsv)"
ok "subscription: ${SUB_NAME} (${SUB_ID})"
ok "user:         ${USER_UPN} (${USER_OID})"

substep "Generate suffix"
# Use openssl (always available alongside git) to avoid SIGPIPE from tr|head
# under `set -o pipefail` on Git Bash.
SUFFIX="$(openssl rand -hex 2)"
PROJECT="${PROJECT:-vinex22}"
ok "PROJECT=${PROJECT}  OWNER_SUFFIX=${SUFFIX}"
info "Resource names will be:"
cat <<EOF
    resource group : rg-${PROJECT}-${SUFFIX}
    AKS            : aks-${PROJECT}-${SUFFIX}
    ACR            : acr${PROJECT}${SUFFIX}
    Postgres Flex  : pg-${PROJECT}-${SUFFIX}
    Service Bus    : sb-${PROJECT}-${SUFFIX}
    Redis          : redis-${PROJECT}-${SUFFIX}
    Storage        : st${PROJECT}${SUFFIX}
    Key Vault      : kv-${PROJECT}-${SUFFIX}
    UAMI           : id-${PROJECT}-${SUFFIX}
EOF

substep "Write ${ENV_FILE}"
cat >"${ENV_FILE}" <<EOF
# Generated by scripts/init-names.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT — this file is in .gitignore.
export PROJECT="${PROJECT}"
export OWNER_SUFFIX="${SUFFIX}"
export AZ_SUBSCRIPTION_ID="${SUB_ID}"
export AZ_USER_OBJECT_ID="${USER_OID}"
export AZ_USER_UPN="${USER_UPN}"
export AZ_LOCATION="\${AZ_LOCATION:-centralindia}"

# Derived names (kept in sync with Terraform locals)
export RG_NAME="rg-${PROJECT}-${SUFFIX}"
export AKS_NAME="aks-${PROJECT}-${SUFFIX}"
export ACR_NAME="acr${PROJECT}${SUFFIX}"
export PG_NAME="pg-${PROJECT}-${SUFFIX}"
export SB_NAME="sb-${PROJECT}-${SUFFIX}"
export REDIS_NAME="redis-${PROJECT}-${SUFFIX}"
export STORAGE_NAME="st${PROJECT}${SUFFIX}"
export KEYVAULT_NAME="kv-${PROJECT}-${SUFFIX}"
export UAMI_NAME="id-${PROJECT}-${SUFFIX}"
EOF
chmod 600 "${ENV_FILE}"
ok "wrote ${ENV_FILE}"

substep "Write ${TFVARS}"
if [[ -f "${TFVARS}" ]]; then
  warn "${TFVARS} already exists — leaving it alone."
else
  cat >"${TFVARS}" <<EOF
# Generated by scripts/init-names.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
subscription_id        = "${SUB_ID}"
current_user_object_id = "${USER_OID}"
current_user_upn       = "${USER_UPN}"
owner_suffix           = "${SUFFIX}"
project                = "${PROJECT}"
EOF
  ok "wrote ${TFVARS}"
fi
